# Пайплайн: проект классификации Ирисов

##  Собираем днанные

In [43]:
import requests as rq
import pandas as pd
from sklearn import datasets
import pandas as pd

FEATURES_IRIS_RAW = 'features_iris.csv'
TARGET_RAW = 'target.csv'


def save_raw():
    iris = datasets.load_iris()
    iris_df=pd.DataFrame(iris.data)


    iris_df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid']
    iris_df['index'] = iris_df.index
    iris_df.dropna(how="all", inplace=True)
    iris_df.to_csv(FEATURES_IRIS_RAW, index = False)

    target_df = pd.DataFrame(iris.target)
    target_df['index'] = target_df.index
    target_df.columns=['target','index']
    target_df.dropna(how="all", inplace=True)
    iris_df.to_csv(TARGET_RAW, index = False)

save_raw()

In [40]:
iris_df=pd.DataFrame(iris.data)
iris_df.columns

RangeIndex(start=0, stop=4, step=1)

In [39]:
iris_df

     sepal_len  sepal_wid  petal_len  petal_wid  index
0          5.1        3.5        1.4        0.2      0
1          4.9        3.0        1.4        0.2      1
2          4.7        3.2        1.3        0.2      2
3          4.6        3.1        1.5        0.2      3
4          5.0        3.6        1.4        0.2      4
..         ...        ...        ...        ...    ...
145        6.7        3.0        5.2        2.3    145
146        6.3        2.5        5.0        1.9    146
147        6.5        3.0        5.2        2.0    147
148        6.2        3.4        5.4        2.3    148
149        5.9        3.0        5.1        1.8    149

[150 rows x 5 columns]

In [20]:
pd.read_csv('features_iris.csv')

     sepal_len  sepal_wid  petal_len  petal_wid  index
0          5.1        3.5        1.4        0.2      0
1          4.9        3.0        1.4        0.2      1
2          4.7        3.2        1.3        0.2      2
3          4.6        3.1        1.5        0.2      3
4          5.0        3.6        1.4        0.2      4
..         ...        ...        ...        ...    ...
145        6.7        3.0        5.2        2.3    145
146        6.3        2.5        5.0        1.9    146
147        6.5        3.0        5.2        2.0    147
148        6.2        3.4        5.4        2.3    148
149        5.9        3.0        5.1        1.8    149

[150 rows x 5 columns]

In [22]:
import json

FEATURES_FIELD = 'data'
TARGET_FIELD = 'target'
SAVE_FIELDS = [FEATURES_FIELD,TARGET_FIELD]

def save_raw(data,name):
    with open(name,'w') as f:
        json.dump(data, f)
        
raw_features_iris = {
    FEATURES_FIELD: [
        list(i)   
        for i in iris[FEATURES_FIELD]
    ]
}

target_iris = {
    TARGET_FIELD: [
        int(i)  
        for i in iris[TARGET_FIELD]
    ]
}

save_raw(raw_features_iris, 'features.json')
save_raw(target_iris, 'target.json')

In [23]:
# -- project 
#       -- jupyter - а чем плох? (вопрос в зал)   
#       -- stage1 (разбить пайлайн на файлики процессов: скачивание данных, сохранение таргета, 
#       сохранение фичей, мердж, препроцессинг)


#       -- mlflow (client.py*)


#       -- dvc.yaml (запуск пайлайна из строки)


#       -- airflow на рельсах (docker-compose.yaml + dags.py ) - не начинать в домашке 
#          с новой тезнологии с 0 - желательно познакомить максимально, а потом утяжелить

#.      -- streamlint

In [24]:
with open('features.json','r') as f:
    data = json.load(f)

In [31]:
target_iris

{'target': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2]}

In [26]:
target_df =  pd.DataFrame()

target_df['class'] = iris.target
target_df['index'] = target_df.index

target_df.to_csv('target.csv', index = False)

In [27]:
df = pd.read_csv('features_iris.csv')

In [28]:
df

     sepal_len  sepal_wid  petal_len  petal_wid  index
0          5.1        3.5        1.4        0.2      0
1          4.9        3.0        1.4        0.2      1
2          4.7        3.2        1.3        0.2      2
3          4.6        3.1        1.5        0.2      3
4          5.0        3.6        1.4        0.2      4
..         ...        ...        ...        ...    ...
145        6.7        3.0        5.2        2.3    145
146        6.3        2.5        5.0        1.9    146
147        6.5        3.0        5.2        2.0    147
148        6.2        3.4        5.4        2.3    148
149        5.9        3.0        5.1        1.8    149

[150 rows x 5 columns]